### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by jbergstroem** [yostudios/Spritemapper#4]
While discussed at work, this doesn't feel like the most important thing to do since no one in web development uses Python 3, but for completeness, future proof and since py3 is actually considered stable's sake - lets have it open.

Running a 2to3 against the entire repo will give:

<pre>

# PYTHONPATH=build/lib nosetests3
......E...
======================================================================
ERROR: tests.test_parser.test_reprint_test_files
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.1/site-packages/nose-0.11.0.dev_r601-py3.1.egg/nose/case.py", line 177, in runTest
    self.test(*self.arg)
  File "/home/jbergstroem/Spritemapper/tests/test_parser.py", line 40, in test_reprint_test_files
    reprint(fp.read())
  File "/home/jbergstroem/Spritemapper/tests/test_parser.py", line 19, in reprint
    reprinted = "".join(parser.CSSParser(data=css).iter_print_css())
  File "/home/jbergstroem/Spritemapper/spritecss/css/parser.py", line 549, in iter_print_css
    for event in parser:
  File "/home/jbergstroem/Spritemapper/spritecss/css/parser.py", line 45, in iter_events
    self._emit_events()
  File "/home/jbergstroem/Spritemapper/spritecss/css/parser.py", line 433, in _emit_events
    self.state = self.evaluate()
  File "/home/jbergstroem/Spritemapper/spritecss/css/parser.py", line 451, in evaluate
    next(st)
  File "/home/jbergstroem/Spritemapper/spritecss/css/parser.py", line 308, in __next__
    self.token = tok = next(self.tokens)
  File "/home/jbergstroem/Spritemapper/spritecss/css/parser.py", line 216, in _css_tokenizer_lineno
    for tok in toks:
  File "/home/jbergstroem/Spritemapper/spritecss/css/parser.py", line 204, in _css_tokenizer_lvl1
    if tok.lexeme == "char" and tok.value.isspace():
AttributeError: 'int' object has no attribute 'isspace'

----------------------------------------------------------------------
Ran 10 tests in 0.044s

FAILED (errors=1)
</pre>

**Comment by eskin** [comment]
+1
